name: Techbleat Git Action
run-name: Techbleat Git Action
on: 
 push:
  branches: [main]

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Simple_Test_For_Now:
   runs-on: ubuntu-latest
   steps:
     - name: checkout code from repo
       uses: actions/checkout@v4

     - name: Setup Terraform to implement Cloud Infra
       uses: hashicorp/setup-terraform@v2
       with: 
         terraform_version: 1.3.0

     - name: Terraform init
       run: terraform init

     - name: Terraform Plan
       run: terraform plan

     - name: Terraform Destroy
       run: terraform destroy --auto-approve 
